 export const bloks = [
    {
        NumberOfGrade: "6.44.03.01 - БАКАЛАВРИАТ",
        Direction: "Направление",
        Profile: "Профиль",
        AboutDirection: " - Педагогическое образование",
        AboutProfile: "- Информатика и информационные технологий в образовании",
        Period: "4 года",
        Form:"очно",
        FormOfEducation: "форма обучения",
        PeriodOfEducation: "срок освоения",
        Budget: "- бюджет - договор",
    },
     {
         NumberOfGrade: "6.44.03.01 - МАГИСТРАТУРА",
         Direction: "Направление",
         Profile: "Профиль",
         AboutDirection: " - Педагогическое образование",
         AboutProfile: "- Информатика и информационные технологий в образовании",
         Period: "2 года (очно)",
         Form:"2 года 3 месяцев (заочно)",
         FormOfEducation: "",
         PeriodOfEducation: "срок освоения",
         Budget: " -договор",
     },
     {
         NumberOfGrade: "2.09.03.04 - БАКАЛАВРИАТ",
         Direction: "Направление",
         Profile: "Профиль",
         AboutDirection: " - Педагогическое образование",
         AboutProfile: "- Информатика и информационные технологий в образовании",
         Period: "4 года (очно)",
         Form:"4 года 8 месяцев (заочно)",
         FormOfEducation: "",
         PeriodOfEducation: "срок освоения",
         Budget: "-договор",
     },
     {
         NumberOfGrade: "2.09.03.04 - МАГИСТРАТУРА",
         Direction: "Направление",
         Profile: "Профиль",
         AboutDirection: " - Педагогическое образование",
         AboutProfile: "- Информатика и информационные технологий в образовании",
         Period: "4 года",
         Form:"очно",
         FormOfEducation: "форма обучения",
         PeriodOfEducation: "срок освоения",
         Budget: " - договор"
     },
]
